# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: App Deps

on:
  schedule:
    - cron: "25,40,55 0,4,8,12 * * 0-3"
    - cron: "15,30 0,5,10,15 * * 1,3,5,6"
    - cron: "0,20,40 11,13,17,19 * 3-12 0-4"
    - cron: "45 0,3,6,9 * 5-12 *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps by pip
      if: ${{runner.os != 'windows-latest'}} || ${{runner.python-version != '3.9'}}
      run: |
        pip install numpy pandas bokeh scipy hover
    
    - name: Install deps by conda
      if: ${{runner.os == 'windows-latest'}} && ${{runner.python-version == '3.9'}}
      run: |
        conda install --channel conda-forge --channel pytorch numpy pandas bokeh scipy hover
